version: '2'
services:
  jhipstercrud-app:
    image: jhipstercrud
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://jhipstercrud-mariadb:3306/jhipstercrud?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8085:8085
  jhipstercrud-mariadb:
    extends:
      file: mariadb.yml
      service: jhipstercrud-mariadb
